version: "3.9"
services:
  app:
    container_name: cryptomarket-web
    build:
      context: .
      dockerfile: docker/Dockerfile-apache2
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/conf:/etc/apache2/sites-enabled
    depends_on:
      - db
    links:
      - db
    restart: always
    networks:
        - network
  db:
    container_name: cryptomarket-db
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./var/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      TZ: Europe/Paris
    networks:
      - network
  phpmyadmin:
    container_name: cryptomarket-pma
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - network
volumes:
  caddy_data:
  caddy_config:
networks:
  network:
